language: android
android:
  components:
    - build-tools-20.0.0
    - tools
    - android-20
    - sys-img-armeabi-v7a-android-20
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - android-sdk-preview-license-52d11cd2
before_script:
    - echo no | android create avd --force -n test -t android-20 --abi default/armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
script:
    - travis_retry ./gradlew assemble connectedCheck
